In [1]:
import numpy as np

In [5]:
a=np.array([5,6,7])
a[0]

5

In [12]:
a=np.array([[5,6],[7,8],[1,2]])
a.ndim

2

In [13]:
a.itemsize

4

In [14]:
a.dtype

dtype('int32')

In [15]:
a=np.array([[5,6],[7,8],[1,2]], dtype=np.float64)
a.dtype

dtype('float64')

In [16]:
a.itemsize

8

In [17]:
a.size

6

In [18]:
a

array([[5., 6.],
       [7., 8.],
       [1., 2.]])

In [19]:
a.shape

(3, 2)

In [46]:
a=np.array([[5,6],[7,8],[1,2]])
a

array([[5, 6],
       [7, 8],
       [1, 2]])

In [21]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
l=range(5)
l

range(0, 5)

In [27]:
l[1]

1

In [30]:
np.arange(1,5)

array([1, 2, 3, 4])

In [35]:
np.arange(1,15,2)

array([ 1,  3,  5,  7,  9, 11, 13])

In [40]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [43]:
a.shape

(3, 2)

In [47]:
a

array([[5, 6],
       [7, 8],
       [1, 2]])

In [48]:
a.reshape(2,3)

array([[5, 6, 7],
       [8, 1, 2]])

In [51]:
a.reshape(3,2)

array([[5, 6],
       [7, 8],
       [1, 2]])

In [52]:
a.ravel()

array([5, 6, 7, 8, 1, 2])

In [57]:
a.min()

1

In [59]:
a.max()

8

In [60]:
a.sum()

29

In [61]:
a.sum(axis=0)

array([13, 16])

In [62]:
a.sum(axis=1)

array([11, 15,  3])

In [63]:
np.sqrt(a)

array([[2.23606798, 2.44948974],
       [2.64575131, 2.82842712],
       [1.        , 1.41421356]])

In [64]:
np.std(a)

2.544056253745625

In [65]:
b=np.array([[1,2],[3,4],[5,6]])
a+b

array([[ 6,  8],
       [10, 12],
       [ 6,  8]])

In [66]:
a*b

array([[ 5, 12],
       [21, 32],
       [ 5, 12]])

In [67]:
a/b


array([[5.        , 3.        ],
       [2.33333333, 2.        ],
       [0.2       , 0.33333333]])

In [68]:
2*a+b

array([[11, 14],
       [17, 20],
       [ 7, 10]])

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)